### ISSUE TITLE
Trying to rotate obj

### ISSUE THREAD

**Issue by lajune1** [googlecodelabs/ar-with-webxr#6]
Hi! I am pretty new to three.js and google ar and I have been trying to find a way to animate the obj's that I import into the final example. I have mainly been looking at three.js tutorials on how to do this, however none of the tutorials I view have quite the same syntax as was used in the tutorial making it a little hard for me to translate the code to fit my needs. Are there any other resources to learn more about how rotate and translate the objs on the reticle? I know that I cannot export the animation already on the obj, as obj's do not support that. I am trying to use the code to animate. 

Thanks so much!

**Comment by lajune1** [comment]
Also, is there a way to upload the .gltf so that I can just have the animation baked in to the object instead?

**Comment by jsantell** [comment]
You can use a gltf instead of an obj model, here's a three.js demo doing that: https://threejs.org/examples/?q=gltf#webgl_loader_gltf

If you want to do things like translate and rotate, see this example of updating a mesh in a render loop: https://github.com/mrdoob/three.js/blob/master/examples/webgl_geometry_cube.html

Stack overflow and the three.js examples are good resources to learn from. Hope this helps!

**Comment by alanhzh** [comment]
Can you give an example of how to load GLTF instead of OBJ, because I can only get endless errors when I try to load GLTF objects.
